# Generated by Django 4.2.29 on 2026-03-29 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('mission_type', models.CharField(choices=[('lunar', 'Lunar'), ('mars', 'Mars'), ('orbit', 'Earth Orbit'), ('deep_space', 'Deep Space'), ('iss', 'ISS'), ('satellite', 'Satellite')], default='orbit', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('launch_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('crew_count', models.IntegerField(default=0)),
                ('agency', models.CharField(default='COSMOSX Agency', max_length=100)),
                ('image_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-launch_date'],
            },
        ),
        migrations.CreateModel(
            name='SpacecraftGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('spacecraft_type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=200)),
                ('first_flight', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_portal.mission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('mission', 'Mission Update'), ('research', 'Research'), ('technology', 'Technology'), ('astronaut', 'Astronaut News'), ('general', 'General')], default='general', max_length=20)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, default='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='space_portal.mission')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocket_name', models.CharField(max_length=200)),
                ('launch_site', models.CharField(max_length=200)),
                ('launch_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('launched', 'Launched'), ('delayed', 'Delayed'), ('scrubbed', 'Scrubbed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('countdown_target', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='space_portal.mission')),
            ],
            options={
                'ordering': ['launch_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('training', 'In Training')], default='active', max_length=20)),
                ('bio', models.TextField()),
                ('missions_count', models.IntegerField(default=0)),
                ('hours_in_space', models.FloatField(default=0.0)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('missions', models.ManyToManyField(blank=True, related_name='astronauts', to='space_portal.mission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
